### PR TITLE
Add support for "Shared Drives"

### PR DESCRIPTION
**Pull request by timvlaer**
This PR adds support for Google's "Shared Drives", see https://developers.google.com/drive/api/guides/enable-shareddrives

This PR updates the build to go 1.17

### CODE REVIEW

**Comment by jordanwmckee** [comment]
@adityak74

**Comment by timvlaer** [comment]
@jordanwmckee if you need this functionality, you can use my fork in the meantime:
```
- name: Upload to gdrive
  uses: timvlaer/google-drive-upload-git-action@main
  with:
     ...
```

**Comment by adityak74** [comment]
@timvlaer @jordanwmckee - Thanks for contributing, new release v0.2 is now up!

**Comment by jordanwmckee** [comment]
@timvlaer Awesome, thank you, it works great! Would it be possible to add support for uploading folders as well?

**Comment by adityak74** [comment]
@jordanwmckee - Can you post more specific requirements?

**Comment by jordanwmckee** [comment]
@adityak74- Well, I'm not very familliar with the creation process for these gh actions, so I'm not sure how difficult this would be, but in my current project, I have a directory that contains a few files and other sub-dirs and files. I would like to be able to upload that main directory to a folder in google drive and maintain the structure inside that directory. So in gdrive, it would have to create the new directories in the specified location I am uploading to, and upload the contents of those directories to the destination as well. Does that make sense?

**Pull request merged**
